---
- name: Copy ACE version files
  copy:
    src: "{{ ace_files }}/{{ ace_version }}/ace-{{ ace_version }}"
    dest: "{{ install_dir }}/ace-{{ ace_version }}"
    remote_src: yes

- name: Change directory to the new ACE version and run make command
  command: "./ace make registry global accept license silently"
  args:
    chdir: "{{ install_dir }}/ace-{{ ace_version }}"