---
- name: Apply Fix Pack to ACE12 System
  hosts: all
  tasks:
    - name: Create unique id for the environment
      block:
        - name: create unique id for demo instance
          ansible.builtin.shell:
            cmd: uuidgen | cut -c1-4
          register: demo_uuid_raw
        - name: set unique id fact
          ansible.builtin.set_fact:
            demo_uuid: "{{ demo_uuid_raw.stdout }}"
      when:
        - demo_uuid is not defined

    - name: Apply Patch to ACE 12 on AIX
      ansible.builtin.include_role:
        name: ../roles/ace12_patch